Add tests
andrewda/valid-github-username pull request #4
Opened 2018-10-23 21:06 UTC by kx-chen

Would like feedback on where to go from here. "It works" but I don't think the code is good enough. :)

2018-10-23 21:43 UTC, andrewda requested changes
A few minor changes, but looks awesome overall!

2018-10-23 21:43 UTC, andrewda commented on test.js
> +const validGithubUsername = require("./index");
Capitalize the "H" in GitHub, so: `validGitHubUsername`

2018-10-23 21:43 UTC, andrewda commented on test.js
> +describe("removes illegal characters", function() {
I've been using single quotes everywhere else, so just use single quotes in the tests, too 👍

2018-10-23 21:43 UTC, andrewda commented on test.js
> +   it("removes / , . ^ [] {} <> ! @ # $ % & * () _ + = | ? ' characters", function(){
"removes special characters" would probably be easier to understand

2018-10-23 21:43 UTC, andrewda commented on test.js
> +   it("removes spaces", function() {
If you could also use ES6 arrow functions, that'd be awesome!

```javascript
it('removes spaces', () => {
   // ....
})
```

2018-10-23 21:51 UTC, kx-chen commented
@andrewda Thanks for the feedback! I believe I've addressed the changes. 

Also, I'm not too sure if the commit messages are okay.... any thoughts?

2018-10-23 23:17 UTC, yukiisbored commented
Commit messages are alright :+1:. Personally, I suggest squashing both commits into one since Mocha is a requirement but @andrewda may have a different suggestion.

2018-10-24 02:57 UTC, kx-chen commented
@yukiisbored  Thanks! I'll keep that in mind. I've submitted the task for review, and will see what Andrew thinks.

2018-10-24 03:59 UTC, andrewda approved these changes
I typically squash and merge anyways, so this looks all good!

2018-10-24 04:33 UTC, merged